scoreboard objectives remove bouncy
scoreboard objectives remove powerMultiplier
scoreboard objectives remove blockMultiplier
scoreboard objectives add bouncy dummy
scoreboard objectives add powerMultiplier dummy
scoreboard objectives add blockMultiplier dummy